// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/wtiger001/lair-backend/models"
)

// CancelLaunchOKCode is the HTTP code returned for type CancelLaunchOK
const CancelLaunchOKCode int = 200

/*CancelLaunchOK OK

swagger:response cancelLaunchOK
*/
type CancelLaunchOK struct {

	/*
	  In: Body
	*/
	Payload *models.WorkspaceStatus `json:"body,omitempty"`
}

// NewCancelLaunchOK creates CancelLaunchOK with default headers values
func NewCancelLaunchOK() *CancelLaunchOK {

	return &CancelLaunchOK{}
}

// WithPayload adds the payload to the cancel launch o k response
func (o *CancelLaunchOK) WithPayload(payload *models.WorkspaceStatus) *CancelLaunchOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cancel launch o k response
func (o *CancelLaunchOK) SetPayload(payload *models.WorkspaceStatus) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CancelLaunchOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CancelLaunchBadRequestCode is the HTTP code returned for type CancelLaunchBadRequest
const CancelLaunchBadRequestCode int = 400

/*CancelLaunchBadRequest Invalid Parameters

swagger:response cancelLaunchBadRequest
*/
type CancelLaunchBadRequest struct {
}

// NewCancelLaunchBadRequest creates CancelLaunchBadRequest with default headers values
func NewCancelLaunchBadRequest() *CancelLaunchBadRequest {

	return &CancelLaunchBadRequest{}
}

// WriteResponse to the client
func (o *CancelLaunchBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CancelLaunchUnauthorizedCode is the HTTP code returned for type CancelLaunchUnauthorized
const CancelLaunchUnauthorizedCode int = 401

/*CancelLaunchUnauthorized Unauthenticated

swagger:response cancelLaunchUnauthorized
*/
type CancelLaunchUnauthorized struct {
}

// NewCancelLaunchUnauthorized creates CancelLaunchUnauthorized with default headers values
func NewCancelLaunchUnauthorized() *CancelLaunchUnauthorized {

	return &CancelLaunchUnauthorized{}
}

// WriteResponse to the client
func (o *CancelLaunchUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// CancelLaunchForbiddenCode is the HTTP code returned for type CancelLaunchForbidden
const CancelLaunchForbiddenCode int = 403

/*CancelLaunchForbidden User is not authorized to perform this action

swagger:response cancelLaunchForbidden
*/
type CancelLaunchForbidden struct {
}

// NewCancelLaunchForbidden creates CancelLaunchForbidden with default headers values
func NewCancelLaunchForbidden() *CancelLaunchForbidden {

	return &CancelLaunchForbidden{}
}

// WriteResponse to the client
func (o *CancelLaunchForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// CancelLaunchNotFoundCode is the HTTP code returned for type CancelLaunchNotFound
const CancelLaunchNotFoundCode int = 404

/*CancelLaunchNotFound Workspace not found

swagger:response cancelLaunchNotFound
*/
type CancelLaunchNotFound struct {
}

// NewCancelLaunchNotFound creates CancelLaunchNotFound with default headers values
func NewCancelLaunchNotFound() *CancelLaunchNotFound {

	return &CancelLaunchNotFound{}
}

// WriteResponse to the client
func (o *CancelLaunchNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// CancelLaunchInternalServerErrorCode is the HTTP code returned for type CancelLaunchInternalServerError
const CancelLaunchInternalServerErrorCode int = 500

/*CancelLaunchInternalServerError Internal Server Error

swagger:response cancelLaunchInternalServerError
*/
type CancelLaunchInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewCancelLaunchInternalServerError creates CancelLaunchInternalServerError with default headers values
func NewCancelLaunchInternalServerError() *CancelLaunchInternalServerError {

	return &CancelLaunchInternalServerError{}
}

// WithPayload adds the payload to the cancel launch internal server error response
func (o *CancelLaunchInternalServerError) WithPayload(payload string) *CancelLaunchInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cancel launch internal server error response
func (o *CancelLaunchInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CancelLaunchInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
