// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteWorkpaceByIDOKCode is the HTTP code returned for type DeleteWorkpaceByIDOK
const DeleteWorkpaceByIDOKCode int = 200

/*DeleteWorkpaceByIDOK OK

swagger:response deleteWorkpaceByIdOK
*/
type DeleteWorkpaceByIDOK struct {
}

// NewDeleteWorkpaceByIDOK creates DeleteWorkpaceByIDOK with default headers values
func NewDeleteWorkpaceByIDOK() *DeleteWorkpaceByIDOK {

	return &DeleteWorkpaceByIDOK{}
}

// WriteResponse to the client
func (o *DeleteWorkpaceByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteWorkpaceByIDBadRequestCode is the HTTP code returned for type DeleteWorkpaceByIDBadRequest
const DeleteWorkpaceByIDBadRequestCode int = 400

/*DeleteWorkpaceByIDBadRequest Invalid Parameters

swagger:response deleteWorkpaceByIdBadRequest
*/
type DeleteWorkpaceByIDBadRequest struct {
}

// NewDeleteWorkpaceByIDBadRequest creates DeleteWorkpaceByIDBadRequest with default headers values
func NewDeleteWorkpaceByIDBadRequest() *DeleteWorkpaceByIDBadRequest {

	return &DeleteWorkpaceByIDBadRequest{}
}

// WriteResponse to the client
func (o *DeleteWorkpaceByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// DeleteWorkpaceByIDUnauthorizedCode is the HTTP code returned for type DeleteWorkpaceByIDUnauthorized
const DeleteWorkpaceByIDUnauthorizedCode int = 401

/*DeleteWorkpaceByIDUnauthorized Unauthenticated

swagger:response deleteWorkpaceByIdUnauthorized
*/
type DeleteWorkpaceByIDUnauthorized struct {
}

// NewDeleteWorkpaceByIDUnauthorized creates DeleteWorkpaceByIDUnauthorized with default headers values
func NewDeleteWorkpaceByIDUnauthorized() *DeleteWorkpaceByIDUnauthorized {

	return &DeleteWorkpaceByIDUnauthorized{}
}

// WriteResponse to the client
func (o *DeleteWorkpaceByIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// DeleteWorkpaceByIDForbiddenCode is the HTTP code returned for type DeleteWorkpaceByIDForbidden
const DeleteWorkpaceByIDForbiddenCode int = 403

/*DeleteWorkpaceByIDForbidden User is not authorized to perform this action

swagger:response deleteWorkpaceByIdForbidden
*/
type DeleteWorkpaceByIDForbidden struct {
}

// NewDeleteWorkpaceByIDForbidden creates DeleteWorkpaceByIDForbidden with default headers values
func NewDeleteWorkpaceByIDForbidden() *DeleteWorkpaceByIDForbidden {

	return &DeleteWorkpaceByIDForbidden{}
}

// WriteResponse to the client
func (o *DeleteWorkpaceByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// DeleteWorkpaceByIDNotFoundCode is the HTTP code returned for type DeleteWorkpaceByIDNotFound
const DeleteWorkpaceByIDNotFoundCode int = 404

/*DeleteWorkpaceByIDNotFound Workspace not found

swagger:response deleteWorkpaceByIdNotFound
*/
type DeleteWorkpaceByIDNotFound struct {
}

// NewDeleteWorkpaceByIDNotFound creates DeleteWorkpaceByIDNotFound with default headers values
func NewDeleteWorkpaceByIDNotFound() *DeleteWorkpaceByIDNotFound {

	return &DeleteWorkpaceByIDNotFound{}
}

// WriteResponse to the client
func (o *DeleteWorkpaceByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// DeleteWorkpaceByIDInternalServerErrorCode is the HTTP code returned for type DeleteWorkpaceByIDInternalServerError
const DeleteWorkpaceByIDInternalServerErrorCode int = 500

/*DeleteWorkpaceByIDInternalServerError Internal Server Error

swagger:response deleteWorkpaceByIdInternalServerError
*/
type DeleteWorkpaceByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewDeleteWorkpaceByIDInternalServerError creates DeleteWorkpaceByIDInternalServerError with default headers values
func NewDeleteWorkpaceByIDInternalServerError() *DeleteWorkpaceByIDInternalServerError {

	return &DeleteWorkpaceByIDInternalServerError{}
}

// WithPayload adds the payload to the delete workpace by Id internal server error response
func (o *DeleteWorkpaceByIDInternalServerError) WithPayload(payload string) *DeleteWorkpaceByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete workpace by Id internal server error response
func (o *DeleteWorkpaceByIDInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteWorkpaceByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
