// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetWorkspacesIDHandlerFunc turns a function with the right signature into a get workspaces ID handler
type GetWorkspacesIDHandlerFunc func(GetWorkspacesIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWorkspacesIDHandlerFunc) Handle(params GetWorkspacesIDParams) middleware.Responder {
	return fn(params)
}

// GetWorkspacesIDHandler interface for that can handle valid get workspaces ID params
type GetWorkspacesIDHandler interface {
	Handle(GetWorkspacesIDParams) middleware.Responder
}

// NewGetWorkspacesID creates a new http.Handler for the get workspaces ID operation
func NewGetWorkspacesID(ctx *middleware.Context, handler GetWorkspacesIDHandler) *GetWorkspacesID {
	return &GetWorkspacesID{Context: ctx, Handler: handler}
}

/*GetWorkspacesID swagger:route GET /workspaces/{id} getWorkspacesId

Returns a workspace

*/
type GetWorkspacesID struct {
	Context *middleware.Context
	Handler GetWorkspacesIDHandler
}

func (o *GetWorkspacesID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetWorkspacesIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
