// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/wtiger001/lair-backend/models"
)

// GetWorkspacesIDOKCode is the HTTP code returned for type GetWorkspacesIDOK
const GetWorkspacesIDOKCode int = 200

/*GetWorkspacesIDOK OK

swagger:response getWorkspacesIdOK
*/
type GetWorkspacesIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Workspace `json:"body,omitempty"`
}

// NewGetWorkspacesIDOK creates GetWorkspacesIDOK with default headers values
func NewGetWorkspacesIDOK() *GetWorkspacesIDOK {

	return &GetWorkspacesIDOK{}
}

// WithPayload adds the payload to the get workspaces Id o k response
func (o *GetWorkspacesIDOK) WithPayload(payload *models.Workspace) *GetWorkspacesIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get workspaces Id o k response
func (o *GetWorkspacesIDOK) SetPayload(payload *models.Workspace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWorkspacesIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetWorkspacesIDBadRequestCode is the HTTP code returned for type GetWorkspacesIDBadRequest
const GetWorkspacesIDBadRequestCode int = 400

/*GetWorkspacesIDBadRequest Invalid Parameters

swagger:response getWorkspacesIdBadRequest
*/
type GetWorkspacesIDBadRequest struct {
}

// NewGetWorkspacesIDBadRequest creates GetWorkspacesIDBadRequest with default headers values
func NewGetWorkspacesIDBadRequest() *GetWorkspacesIDBadRequest {

	return &GetWorkspacesIDBadRequest{}
}

// WriteResponse to the client
func (o *GetWorkspacesIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetWorkspacesIDUnauthorizedCode is the HTTP code returned for type GetWorkspacesIDUnauthorized
const GetWorkspacesIDUnauthorizedCode int = 401

/*GetWorkspacesIDUnauthorized Unauthenticated

swagger:response getWorkspacesIdUnauthorized
*/
type GetWorkspacesIDUnauthorized struct {
}

// NewGetWorkspacesIDUnauthorized creates GetWorkspacesIDUnauthorized with default headers values
func NewGetWorkspacesIDUnauthorized() *GetWorkspacesIDUnauthorized {

	return &GetWorkspacesIDUnauthorized{}
}

// WriteResponse to the client
func (o *GetWorkspacesIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetWorkspacesIDForbiddenCode is the HTTP code returned for type GetWorkspacesIDForbidden
const GetWorkspacesIDForbiddenCode int = 403

/*GetWorkspacesIDForbidden User is not authorized to perform this action

swagger:response getWorkspacesIdForbidden
*/
type GetWorkspacesIDForbidden struct {
}

// NewGetWorkspacesIDForbidden creates GetWorkspacesIDForbidden with default headers values
func NewGetWorkspacesIDForbidden() *GetWorkspacesIDForbidden {

	return &GetWorkspacesIDForbidden{}
}

// WriteResponse to the client
func (o *GetWorkspacesIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetWorkspacesIDNotFoundCode is the HTTP code returned for type GetWorkspacesIDNotFound
const GetWorkspacesIDNotFoundCode int = 404

/*GetWorkspacesIDNotFound Workspace not found

swagger:response getWorkspacesIdNotFound
*/
type GetWorkspacesIDNotFound struct {
}

// NewGetWorkspacesIDNotFound creates GetWorkspacesIDNotFound with default headers values
func NewGetWorkspacesIDNotFound() *GetWorkspacesIDNotFound {

	return &GetWorkspacesIDNotFound{}
}

// WriteResponse to the client
func (o *GetWorkspacesIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetWorkspacesIDInternalServerErrorCode is the HTTP code returned for type GetWorkspacesIDInternalServerError
const GetWorkspacesIDInternalServerErrorCode int = 500

/*GetWorkspacesIDInternalServerError Internal Server Error

swagger:response getWorkspacesIdInternalServerError
*/
type GetWorkspacesIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetWorkspacesIDInternalServerError creates GetWorkspacesIDInternalServerError with default headers values
func NewGetWorkspacesIDInternalServerError() *GetWorkspacesIDInternalServerError {

	return &GetWorkspacesIDInternalServerError{}
}

// WithPayload adds the payload to the get workspaces Id internal server error response
func (o *GetWorkspacesIDInternalServerError) WithPayload(payload string) *GetWorkspacesIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get workspaces Id internal server error response
func (o *GetWorkspacesIDInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWorkspacesIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
