// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/wtiger001/lair-backend/models"
)

// GetWorkspaceByIDOKCode is the HTTP code returned for type GetWorkspaceByIDOK
const GetWorkspaceByIDOKCode int = 200

/*GetWorkspaceByIDOK OK

swagger:response getWorkspaceByIdOK
*/
type GetWorkspaceByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Workspace `json:"body,omitempty"`
}

// NewGetWorkspaceByIDOK creates GetWorkspaceByIDOK with default headers values
func NewGetWorkspaceByIDOK() *GetWorkspaceByIDOK {

	return &GetWorkspaceByIDOK{}
}

// WithPayload adds the payload to the get workspace by Id o k response
func (o *GetWorkspaceByIDOK) WithPayload(payload *models.Workspace) *GetWorkspaceByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get workspace by Id o k response
func (o *GetWorkspaceByIDOK) SetPayload(payload *models.Workspace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWorkspaceByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetWorkspaceByIDBadRequestCode is the HTTP code returned for type GetWorkspaceByIDBadRequest
const GetWorkspaceByIDBadRequestCode int = 400

/*GetWorkspaceByIDBadRequest Invalid Parameters

swagger:response getWorkspaceByIdBadRequest
*/
type GetWorkspaceByIDBadRequest struct {
}

// NewGetWorkspaceByIDBadRequest creates GetWorkspaceByIDBadRequest with default headers values
func NewGetWorkspaceByIDBadRequest() *GetWorkspaceByIDBadRequest {

	return &GetWorkspaceByIDBadRequest{}
}

// WriteResponse to the client
func (o *GetWorkspaceByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetWorkspaceByIDUnauthorizedCode is the HTTP code returned for type GetWorkspaceByIDUnauthorized
const GetWorkspaceByIDUnauthorizedCode int = 401

/*GetWorkspaceByIDUnauthorized Unauthenticated

swagger:response getWorkspaceByIdUnauthorized
*/
type GetWorkspaceByIDUnauthorized struct {
}

// NewGetWorkspaceByIDUnauthorized creates GetWorkspaceByIDUnauthorized with default headers values
func NewGetWorkspaceByIDUnauthorized() *GetWorkspaceByIDUnauthorized {

	return &GetWorkspaceByIDUnauthorized{}
}

// WriteResponse to the client
func (o *GetWorkspaceByIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetWorkspaceByIDForbiddenCode is the HTTP code returned for type GetWorkspaceByIDForbidden
const GetWorkspaceByIDForbiddenCode int = 403

/*GetWorkspaceByIDForbidden User is not authorized to perform this action

swagger:response getWorkspaceByIdForbidden
*/
type GetWorkspaceByIDForbidden struct {
}

// NewGetWorkspaceByIDForbidden creates GetWorkspaceByIDForbidden with default headers values
func NewGetWorkspaceByIDForbidden() *GetWorkspaceByIDForbidden {

	return &GetWorkspaceByIDForbidden{}
}

// WriteResponse to the client
func (o *GetWorkspaceByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// GetWorkspaceByIDNotFoundCode is the HTTP code returned for type GetWorkspaceByIDNotFound
const GetWorkspaceByIDNotFoundCode int = 404

/*GetWorkspaceByIDNotFound Workspace not found

swagger:response getWorkspaceByIdNotFound
*/
type GetWorkspaceByIDNotFound struct {
}

// NewGetWorkspaceByIDNotFound creates GetWorkspaceByIDNotFound with default headers values
func NewGetWorkspaceByIDNotFound() *GetWorkspaceByIDNotFound {

	return &GetWorkspaceByIDNotFound{}
}

// WriteResponse to the client
func (o *GetWorkspaceByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetWorkspaceByIDInternalServerErrorCode is the HTTP code returned for type GetWorkspaceByIDInternalServerError
const GetWorkspaceByIDInternalServerErrorCode int = 500

/*GetWorkspaceByIDInternalServerError Internal Server Error

swagger:response getWorkspaceByIdInternalServerError
*/
type GetWorkspaceByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetWorkspaceByIDInternalServerError creates GetWorkspaceByIDInternalServerError with default headers values
func NewGetWorkspaceByIDInternalServerError() *GetWorkspaceByIDInternalServerError {

	return &GetWorkspaceByIDInternalServerError{}
}

// WithPayload adds the payload to the get workspace by Id internal server error response
func (o *GetWorkspaceByIDInternalServerError) WithPayload(payload string) *GetWorkspaceByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get workspace by Id internal server error response
func (o *GetWorkspaceByIDInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWorkspaceByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
