// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/wtiger001/lair-backend/models"
)

// GetWorkspacesHandlerFunc turns a function with the right signature into a get workspaces handler
type GetWorkspacesHandlerFunc func(GetWorkspacesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWorkspacesHandlerFunc) Handle(params GetWorkspacesParams) middleware.Responder {
	return fn(params)
}

// GetWorkspacesHandler interface for that can handle valid get workspaces params
type GetWorkspacesHandler interface {
	Handle(GetWorkspacesParams) middleware.Responder
}

// NewGetWorkspaces creates a new http.Handler for the get workspaces operation
func NewGetWorkspaces(ctx *middleware.Context, handler GetWorkspacesHandler) *GetWorkspaces {
	return &GetWorkspaces{Context: ctx, Handler: handler}
}

/*GetWorkspaces swagger:route GET /workspaces getWorkspaces

Returns a list workspaces for the calling user.

The users name is expected to be in a JWT.

*/
type GetWorkspaces struct {
	Context *middleware.Context
	Handler GetWorkspacesHandler
}

func (o *GetWorkspaces) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetWorkspacesParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetWorkspacesOKBody get workspaces o k body
//
// swagger:model GetWorkspacesOKBody
type GetWorkspacesOKBody struct {

	// user
	User string `json:"user,omitempty"`

	// workspaces
	Workspaces []*models.Workspace `json:"workspaces"`
}

// Validate validates this get workspaces o k body
func (o *GetWorkspacesOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateWorkspaces(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWorkspacesOKBody) validateWorkspaces(formats strfmt.Registry) error {

	if swag.IsZero(o.Workspaces) { // not required
		return nil
	}

	for i := 0; i < len(o.Workspaces); i++ {
		if swag.IsZero(o.Workspaces[i]) { // not required
			continue
		}

		if o.Workspaces[i] != nil {
			if err := o.Workspaces[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getWorkspacesOK" + "." + "workspaces" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetWorkspacesOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetWorkspacesOKBody) UnmarshalBinary(b []byte) error {
	var res GetWorkspacesOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
