// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetWorkspacesOKCode is the HTTP code returned for type GetWorkspacesOK
const GetWorkspacesOKCode int = 200

/*GetWorkspacesOK OK

swagger:response getWorkspacesOK
*/
type GetWorkspacesOK struct {

	/*
	  In: Body
	*/
	Payload *GetWorkspacesOKBody `json:"body,omitempty"`
}

// NewGetWorkspacesOK creates GetWorkspacesOK with default headers values
func NewGetWorkspacesOK() *GetWorkspacesOK {

	return &GetWorkspacesOK{}
}

// WithPayload adds the payload to the get workspaces o k response
func (o *GetWorkspacesOK) WithPayload(payload *GetWorkspacesOKBody) *GetWorkspacesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get workspaces o k response
func (o *GetWorkspacesOK) SetPayload(payload *GetWorkspacesOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWorkspacesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetWorkspacesUnauthorizedCode is the HTTP code returned for type GetWorkspacesUnauthorized
const GetWorkspacesUnauthorizedCode int = 401

/*GetWorkspacesUnauthorized Unauthenticated

swagger:response getWorkspacesUnauthorized
*/
type GetWorkspacesUnauthorized struct {
}

// NewGetWorkspacesUnauthorized creates GetWorkspacesUnauthorized with default headers values
func NewGetWorkspacesUnauthorized() *GetWorkspacesUnauthorized {

	return &GetWorkspacesUnauthorized{}
}

// WriteResponse to the client
func (o *GetWorkspacesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// GetWorkspacesInternalServerErrorCode is the HTTP code returned for type GetWorkspacesInternalServerError
const GetWorkspacesInternalServerErrorCode int = 500

/*GetWorkspacesInternalServerError Internal Server Error

swagger:response getWorkspacesInternalServerError
*/
type GetWorkspacesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetWorkspacesInternalServerError creates GetWorkspacesInternalServerError with default headers values
func NewGetWorkspacesInternalServerError() *GetWorkspacesInternalServerError {

	return &GetWorkspacesInternalServerError{}
}

// WithPayload adds the payload to the get workspaces internal server error response
func (o *GetWorkspacesInternalServerError) WithPayload(payload string) *GetWorkspacesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get workspaces internal server error response
func (o *GetWorkspacesInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWorkspacesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
