// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewLairBackendAPI creates a new LairBackend instance
func NewLairBackendAPI(spec *loads.Document) *LairBackendAPI {
	return &LairBackendAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		GetWorkspacesHandler: GetWorkspacesHandlerFunc(func(params GetWorkspacesParams) middleware.Responder {
			return middleware.NotImplemented("operation GetWorkspaces has not yet been implemented")
		}),
		GetWorkspacesIDHandler: GetWorkspacesIDHandlerFunc(func(params GetWorkspacesIDParams) middleware.Responder {
			return middleware.NotImplemented("operation GetWorkspacesID has not yet been implemented")
		}),
		CancelLaunchHandler: CancelLaunchHandlerFunc(func(params CancelLaunchParams) middleware.Responder {
			return middleware.NotImplemented("operation CancelLaunch has not yet been implemented")
		}),
		DeleteWorkpaceByIDHandler: DeleteWorkpaceByIDHandlerFunc(func(params DeleteWorkpaceByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteWorkpaceByID has not yet been implemented")
		}),
		GetWorkpaceLaunchStatusHandler: GetWorkpaceLaunchStatusHandlerFunc(func(params GetWorkpaceLaunchStatusParams) middleware.Responder {
			return middleware.NotImplemented("operation GetWorkpaceLaunchStatus has not yet been implemented")
		}),
		LaunchWorkpaceByIDHandler: LaunchWorkpaceByIDHandlerFunc(func(params LaunchWorkpaceByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation LaunchWorkpaceByID has not yet been implemented")
		}),
		PostWorkpaceByIDHandler: PostWorkpaceByIDHandlerFunc(func(params PostWorkpaceByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PostWorkpaceByID has not yet been implemented")
		}),
		PutWorkpaceByIDHandler: PutWorkpaceByIDHandlerFunc(func(params PutWorkpaceByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PutWorkpaceByID has not yet been implemented")
		}),
	}
}

/*LairBackendAPI API for running coading lair actions */
type LairBackendAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// GetWorkspacesHandler sets the operation handler for the get workspaces operation
	GetWorkspacesHandler GetWorkspacesHandler
	// GetWorkspacesIDHandler sets the operation handler for the get workspaces ID operation
	GetWorkspacesIDHandler GetWorkspacesIDHandler
	// CancelLaunchHandler sets the operation handler for the cancel launch operation
	CancelLaunchHandler CancelLaunchHandler
	// DeleteWorkpaceByIDHandler sets the operation handler for the delete workpace by Id operation
	DeleteWorkpaceByIDHandler DeleteWorkpaceByIDHandler
	// GetWorkpaceLaunchStatusHandler sets the operation handler for the get workpace launch status operation
	GetWorkpaceLaunchStatusHandler GetWorkpaceLaunchStatusHandler
	// LaunchWorkpaceByIDHandler sets the operation handler for the launch workpace by Id operation
	LaunchWorkpaceByIDHandler LaunchWorkpaceByIDHandler
	// PostWorkpaceByIDHandler sets the operation handler for the post workpace by Id operation
	PostWorkpaceByIDHandler PostWorkpaceByIDHandler
	// PutWorkpaceByIDHandler sets the operation handler for the put workpace by Id operation
	PutWorkpaceByIDHandler PutWorkpaceByIDHandler
	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *LairBackendAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *LairBackendAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *LairBackendAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *LairBackendAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *LairBackendAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *LairBackendAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *LairBackendAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the LairBackendAPI
func (o *LairBackendAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.GetWorkspacesHandler == nil {
		unregistered = append(unregistered, "GetWorkspacesHandler")
	}
	if o.GetWorkspacesIDHandler == nil {
		unregistered = append(unregistered, "GetWorkspacesIDHandler")
	}
	if o.CancelLaunchHandler == nil {
		unregistered = append(unregistered, "CancelLaunchHandler")
	}
	if o.DeleteWorkpaceByIDHandler == nil {
		unregistered = append(unregistered, "DeleteWorkpaceByIDHandler")
	}
	if o.GetWorkpaceLaunchStatusHandler == nil {
		unregistered = append(unregistered, "GetWorkpaceLaunchStatusHandler")
	}
	if o.LaunchWorkpaceByIDHandler == nil {
		unregistered = append(unregistered, "LaunchWorkpaceByIDHandler")
	}
	if o.PostWorkpaceByIDHandler == nil {
		unregistered = append(unregistered, "PostWorkpaceByIDHandler")
	}
	if o.PutWorkpaceByIDHandler == nil {
		unregistered = append(unregistered, "PutWorkpaceByIDHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *LairBackendAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *LairBackendAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *LairBackendAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
// MIME type parameters are ignored here.
func (o *LairBackendAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result
}

// ProducersFor gets the producers for the specified media types.
// MIME type parameters are ignored here.
func (o *LairBackendAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		switch mt {
		case "application/json":
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *LairBackendAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the lair backend API
func (o *LairBackendAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *LairBackendAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/workspaces"] = NewGetWorkspaces(o.context, o.GetWorkspacesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/workspaces/{id}"] = NewGetWorkspacesID(o.context, o.GetWorkspacesIDHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/workspaces/{id}/launch"] = NewCancelLaunch(o.context, o.CancelLaunchHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/workspaces/{id}"] = NewDeleteWorkpaceByID(o.context, o.DeleteWorkpaceByIDHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/workspaces/{id}/launch"] = NewGetWorkpaceLaunchStatus(o.context, o.GetWorkpaceLaunchStatusHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/workspaces/{id}/launch"] = NewLaunchWorkpaceByID(o.context, o.LaunchWorkpaceByIDHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/workspaces/{id}"] = NewPostWorkpaceByID(o.context, o.PostWorkpaceByIDHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/workspaces/{id}"] = NewPutWorkpaceByID(o.context, o.PutWorkpaceByIDHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *LairBackendAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *LairBackendAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *LairBackendAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *LairBackendAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *LairBackendAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[method][path] = builder(h)
	}
}
