// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/wtiger001/lair-backend/models"
)

// PostWorkpaceByIDOKCode is the HTTP code returned for type PostWorkpaceByIDOK
const PostWorkpaceByIDOKCode int = 200

/*PostWorkpaceByIDOK OK

swagger:response postWorkpaceByIdOK
*/
type PostWorkpaceByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Workspace `json:"body,omitempty"`
}

// NewPostWorkpaceByIDOK creates PostWorkpaceByIDOK with default headers values
func NewPostWorkpaceByIDOK() *PostWorkpaceByIDOK {

	return &PostWorkpaceByIDOK{}
}

// WithPayload adds the payload to the post workpace by Id o k response
func (o *PostWorkpaceByIDOK) WithPayload(payload *models.Workspace) *PostWorkpaceByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post workpace by Id o k response
func (o *PostWorkpaceByIDOK) SetPayload(payload *models.Workspace) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostWorkpaceByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostWorkpaceByIDBadRequestCode is the HTTP code returned for type PostWorkpaceByIDBadRequest
const PostWorkpaceByIDBadRequestCode int = 400

/*PostWorkpaceByIDBadRequest Invalid Parameters

swagger:response postWorkpaceByIdBadRequest
*/
type PostWorkpaceByIDBadRequest struct {
}

// NewPostWorkpaceByIDBadRequest creates PostWorkpaceByIDBadRequest with default headers values
func NewPostWorkpaceByIDBadRequest() *PostWorkpaceByIDBadRequest {

	return &PostWorkpaceByIDBadRequest{}
}

// WriteResponse to the client
func (o *PostWorkpaceByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// PostWorkpaceByIDUnauthorizedCode is the HTTP code returned for type PostWorkpaceByIDUnauthorized
const PostWorkpaceByIDUnauthorizedCode int = 401

/*PostWorkpaceByIDUnauthorized Unauthenticated

swagger:response postWorkpaceByIdUnauthorized
*/
type PostWorkpaceByIDUnauthorized struct {
}

// NewPostWorkpaceByIDUnauthorized creates PostWorkpaceByIDUnauthorized with default headers values
func NewPostWorkpaceByIDUnauthorized() *PostWorkpaceByIDUnauthorized {

	return &PostWorkpaceByIDUnauthorized{}
}

// WriteResponse to the client
func (o *PostWorkpaceByIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}

// PostWorkpaceByIDForbiddenCode is the HTTP code returned for type PostWorkpaceByIDForbidden
const PostWorkpaceByIDForbiddenCode int = 403

/*PostWorkpaceByIDForbidden User is not authorized to perform this action

swagger:response postWorkpaceByIdForbidden
*/
type PostWorkpaceByIDForbidden struct {
}

// NewPostWorkpaceByIDForbidden creates PostWorkpaceByIDForbidden with default headers values
func NewPostWorkpaceByIDForbidden() *PostWorkpaceByIDForbidden {

	return &PostWorkpaceByIDForbidden{}
}

// WriteResponse to the client
func (o *PostWorkpaceByIDForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// PostWorkpaceByIDNotFoundCode is the HTTP code returned for type PostWorkpaceByIDNotFound
const PostWorkpaceByIDNotFoundCode int = 404

/*PostWorkpaceByIDNotFound Workspace not found

swagger:response postWorkpaceByIdNotFound
*/
type PostWorkpaceByIDNotFound struct {
}

// NewPostWorkpaceByIDNotFound creates PostWorkpaceByIDNotFound with default headers values
func NewPostWorkpaceByIDNotFound() *PostWorkpaceByIDNotFound {

	return &PostWorkpaceByIDNotFound{}
}

// WriteResponse to the client
func (o *PostWorkpaceByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// PostWorkpaceByIDInternalServerErrorCode is the HTTP code returned for type PostWorkpaceByIDInternalServerError
const PostWorkpaceByIDInternalServerErrorCode int = 500

/*PostWorkpaceByIDInternalServerError Internal Server Error

swagger:response postWorkpaceByIdInternalServerError
*/
type PostWorkpaceByIDInternalServerError struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewPostWorkpaceByIDInternalServerError creates PostWorkpaceByIDInternalServerError with default headers values
func NewPostWorkpaceByIDInternalServerError() *PostWorkpaceByIDInternalServerError {

	return &PostWorkpaceByIDInternalServerError{}
}

// WithPayload adds the payload to the post workpace by Id internal server error response
func (o *PostWorkpaceByIDInternalServerError) WithPayload(payload string) *PostWorkpaceByIDInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post workpace by Id internal server error response
func (o *PostWorkpaceByIDInternalServerError) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostWorkpaceByIDInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
