// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Lair API
//
//  API for running coading lair actions
//  Schemes:
//    http
//    https
//  Host: api.example.com
//  BasePath: /v1
//  Version: 1.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
