// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for running coading lair actions",
    "title": "Lair API",
    "version": "1.0.0"
  },
  "host": "api.example.com",
  "basePath": "/v1",
  "paths": {
    "/workspaces": {
      "get": {
        "description": "The users name is expected to be in a JWT.",
        "produces": [
          "application/json"
        ],
        "summary": "Returns a list workspaces for the calling user.",
        "operationId": "getWorkspaces",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Workspace"
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/workspaces/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Returns a workspace",
        "operationId": "getWorkspaceById",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "put": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Updates a workspace",
        "operationId": "putWorkpaceById",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Workspace to save",
            "name": "workspace",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Updates a workspace",
        "operationId": "postWorkpaceById",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Workspace to save",
            "name": "workspace",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Deletes a workspace",
        "operationId": "deleteWorkpaceById",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/workspaces/{id}/launch": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Requests a workspace to be launched",
        "operationId": "getWorkpaceLaunchStatus",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WorkspaceStatus"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "produces": [
          "application/json"
        ],
        "summary": "Requests a workspace to be launched",
        "operationId": "launchWorkpaceById",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WorkspaceStatus"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "summary": "Stops a launched workspace",
        "operationId": "cancelLaunch",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "boolean",
            "name": "commitChanges",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WorkspaceStatus"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Workspace": {
      "description": "Workspace",
      "type": "object",
      "properties": {
        "cpus": {
          "description": "Amount of CPU being requested to run this algorithm",
          "type": "number",
          "format": "double"
        },
        "description": {
          "description": "Workspace ID",
          "type": "string"
        },
        "dockerImage": {
          "description": "Full docker image name. Including the repo",
          "type": "string"
        },
        "id": {
          "description": "Workspace ID",
          "type": "string"
        },
        "image": {
          "description": "Image of the workspace",
          "type": "string"
        },
        "memory": {
          "description": "Amount of Memory in MBs being requested",
          "type": "number",
          "format": "double"
        },
        "name": {
          "description": "Workspace ID",
          "type": "string"
        },
        "shared": {
          "description": "If the workpsace is shared for others to clone",
          "type": "boolean"
        },
        "timeout": {
          "description": "Timeout, in minutes, that a workspace will be kept active, default 30 min",
          "type": "number",
          "format": "integer"
        },
        "workpsaceLocation": {
          "description": "Location of the workspace volume",
          "type": "string"
        }
      }
    },
    "WorkspaceStatus": {
      "description": "Workspace Status",
      "type": "object",
      "properties": {
        "id": {
          "description": "Workspace ID / session id",
          "type": "string"
        },
        "status": {
          "description": "Amount of CPU being requested to run this algorithm",
          "type": "string",
          "enum": [
            "none",
            "scheduling",
            "starting",
            "running",
            "stopping"
          ]
        },
        "url": {
          "description": "URL to the running instance",
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https",
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for running coading lair actions",
    "title": "Lair API",
    "version": "1.0.0"
  },
  "host": "api.example.com",
  "basePath": "/v1",
  "paths": {
    "/workspaces": {
      "get": {
        "description": "The users name is expected to be in a JWT.",
        "produces": [
          "application/json"
        ],
        "summary": "Returns a list workspaces for the calling user.",
        "operationId": "getWorkspaces",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Workspace"
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/workspaces/{id}": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Returns a workspace",
        "operationId": "getWorkspaceById",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "put": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Updates a workspace",
        "operationId": "putWorkpaceById",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Workspace to save",
            "name": "workspace",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Updates a workspace",
        "operationId": "postWorkpaceById",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "description": "Workspace to save",
            "name": "workspace",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Workspace"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "delete": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "summary": "Deletes a workspace",
        "operationId": "deleteWorkpaceById",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    },
    "/workspaces/{id}/launch": {
      "get": {
        "produces": [
          "application/json"
        ],
        "summary": "Requests a workspace to be launched",
        "operationId": "getWorkpaceLaunchStatus",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WorkspaceStatus"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "post": {
        "produces": [
          "application/json"
        ],
        "summary": "Requests a workspace to be launched",
        "operationId": "launchWorkpaceById",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WorkspaceStatus"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      },
      "delete": {
        "produces": [
          "application/json"
        ],
        "summary": "Stops a launched workspace",
        "operationId": "cancelLaunch",
        "parameters": [
          {
            "type": "string",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "type": "boolean",
            "name": "commitChanges",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/WorkspaceStatus"
            }
          },
          "400": {
            "description": "Invalid Parameters"
          },
          "401": {
            "description": "Unauthenticated"
          },
          "403": {
            "description": "User is not authorized to perform this action"
          },
          "404": {
            "description": "Workspace not found"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Workspace": {
      "description": "Workspace",
      "type": "object",
      "properties": {
        "cpus": {
          "description": "Amount of CPU being requested to run this algorithm",
          "type": "number",
          "format": "double"
        },
        "description": {
          "description": "Workspace ID",
          "type": "string"
        },
        "dockerImage": {
          "description": "Full docker image name. Including the repo",
          "type": "string"
        },
        "id": {
          "description": "Workspace ID",
          "type": "string"
        },
        "image": {
          "description": "Image of the workspace",
          "type": "string"
        },
        "memory": {
          "description": "Amount of Memory in MBs being requested",
          "type": "number",
          "format": "double"
        },
        "name": {
          "description": "Workspace ID",
          "type": "string"
        },
        "shared": {
          "description": "If the workpsace is shared for others to clone",
          "type": "boolean"
        },
        "timeout": {
          "description": "Timeout, in minutes, that a workspace will be kept active, default 30 min",
          "type": "number",
          "format": "integer"
        },
        "workpsaceLocation": {
          "description": "Location of the workspace volume",
          "type": "string"
        }
      }
    },
    "WorkspaceStatus": {
      "description": "Workspace Status",
      "type": "object",
      "properties": {
        "id": {
          "description": "Workspace ID / session id",
          "type": "string"
        },
        "status": {
          "description": "Amount of CPU being requested to run this algorithm",
          "type": "string",
          "enum": [
            "none",
            "scheduling",
            "starting",
            "running",
            "stopping"
          ]
        },
        "url": {
          "description": "URL to the running instance",
          "type": "string"
        }
      }
    }
  }
}`))
}
